USE DATABASE INSURANCE_DB;
USE SCHEMA RAW;

CREATE OR REPLACE FILE FORMAT CLAIMS_CSV_FORMAT
    TYPE = CSV
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    EMPTY_FIELD_AS_NULL = TRUE
    NULL_IF = ('NULL', 'null');
