USE DATABASE INSURANCE_DB;
USE SCHEMA RAW;

CREATE OR REPLACE STAGE CLAIMS_S3_STAGE
    URL = 's3://insurance-data-engineering-platform-467f70cf/claims/incoming/'
    STORAGE_INTEGRATION = INSURANCE_S3_INTEGRATION;
