USE DATABASE INSURANCE_DB;
USE SCHEMA RAW;

CREATE TABLE IF NOT EXISTS CUSTOMER_RAW
(
    CUSTOMER_ID       VARCHAR,
    FIRST_NAME        VARCHAR,
    LAST_NAME         VARCHAR,
    DATE_OF_BIRTH     VARCHAR,
    EMAIL             VARCHAR,
    PHONE             VARCHAR,
    ADDRESS           VARCHAR,
    CITY              VARCHAR,
    STATE             VARCHAR,
    CUSTOMER_TYPE     VARCHAR,
    CREATED_AT        VARCHAR,
    UPDATED_AT        VARCHAR,

    SOURCE_FILE       VARCHAR,
    FILE_ROW_NUMBER   NUMBER,
    LOAD_TIMESTAMP    TIMESTAMP_NTZ,
    LOAD_BATCH_ID     VARCHAR,
    SOURCE_SYSTEM     VARCHAR,
    RECORD_HASH       VARCHAR
);
