CREATE TABLE IF NOT EXISTS POLICY_RAW
(
    POLICY_ID          VARCHAR,
    CUSTOMER_ID        VARCHAR,
    POLICY_TYPE        VARCHAR,
    POLICY_STATUS      VARCHAR,
    POLICY_START_DATE  VARCHAR,
    POLICY_END_DATE    VARCHAR,
    PREMIUM_AMOUNT     VARCHAR,
    COVERAGE_AMOUNT    VARCHAR,
    AGENT_ID           VARCHAR,
    CREATED_AT         VARCHAR,
    UPDATED_AT         VARCHAR,

    SOURCE_FILE        VARCHAR,
    FILE_ROW_NUMBER    NUMBER,
    LOAD_TIMESTAMP     TIMESTAMP_NTZ,
    LOAD_BATCH_ID      VARCHAR,
    SOURCE_SYSTEM      VARCHAR,
    RECORD_HASH        VARCHAR
);
