CREATE TABLE IF NOT EXISTS AGENT_RAW
(
    AGENT_ID        VARCHAR,
    AGENT_NAME      VARCHAR,
    AGENT_EMAIL     VARCHAR,
    BRANCH          VARCHAR,
    REGION          VARCHAR,
    AGENT_STATUS     VARCHAR,
    CREATED_AT      VARCHAR,
    UPDATED_AT      VARCHAR,

    SOURCE_FILE     VARCHAR,
    FILE_ROW_NUMBER NUMBER,
    LOAD_TIMESTAMP  TIMESTAMP_NTZ,
    LOAD_BATCH_ID   VARCHAR,
    SOURCE_SYSTEM   VARCHAR,
    RECORD_HASH     VARCHAR
);
