USE DATABASE INSURANCE_DB;
USE SCHEMA RAW;

CREATE TABLE IF NOT EXISTS PAYMENT_RAW
(
    RAW_PAYLOAD      VARIANT,

    SOURCE_FILE      VARCHAR,
    FILE_ROW_NUMBER  NUMBER,
    LOAD_TIMESTAMP   TIMESTAMP_NTZ,
    LOAD_BATCH_ID    VARCHAR,
    SOURCE_SYSTEM    VARCHAR,
    RECORD_HASH      VARCHAR
);
